POST http://localhost:8080/holder
Content-Type: application/json

{
  "holderName" : "kevin",
  "tel" : "02-1234-5678",
  "address" : "OO시 OO구"
}

###

POST http://localhost:8080/account
Content-Type: application/json

{
  "holderId" : "a63dee13-3907-4fe7-b711-0fe689edfd1e"
}

###

POST http://localhost:8080/deposit
Content-Type: application/json

{
  "accountId" : "f0869db2-dbd1-43bf-aec6-683f13465513",
  "holderId" : "a63dee13-3907-4fe7-b711-0fe689edfd1e",
  "amount" : 300
}

###

POST http://localhost:8080/withdrawal
Content-Type: application/json

{
  "accountId" : "f0869db2-dbd1-43bf-aec6-683f13465513",
  "holderId" : "a63dee13-3907-4fe7-b711-0fe689edfd1e",
  "amount" : 10
}

###