POST http://localhost:8080/holder
Content-Type: application/json

{
  "holderName" : "rebwon",
  "tel" : "031-1234-5678",
  "address" : "서울시 강남구"
}

###

POST http://localhost:8080/account
Content-Type: application/json

{
  "holderId" : "9f7b9593-1acd-4351-93a3-d77e58007bac"
}

###

POST http://localhost:8080/deposit
Content-Type: application/json

{
  "accountId" : "0111fbd4-5355-4c29-b930-3c43378c1f7e",
  "holderId" : "9f7b9593-1acd-4351-93a3-d77e58007bac",
  "amount" : 300
}

###

POST http://localhost:8080/withdrawal
Content-Type: application/json

{
  "accountId" : "0111fbd4-5355-4c29-b930-3c43378c1f7e",
  "holderId" : "9f7b9593-1acd-4351-93a3-d77e58007bac",
  "amount" : 10
}

###

POST http://localhost:9090/reset