server:
  port: 9090

spring:
  application:
    name: eventsourcing-cqrs-query
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/query?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: query
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

axon:
  serializer:
    general: xstream
  axonserver:
    servers: localhost:8124

logging:
  level:
    com:
      rebwon:
        query: debug
    org:
      axonframework: debug